### ISSUE TITLE
Menubar icon without the percentage disappears

### ISSUE THREAD

**Issue by giuliomagnifico** [thebarbican19/BatteryBoi#15] opened 2023-08-31 11:10 UTC
Hi, very cool app, thanks! But if I disabled the "show percentage" the menubar icon disappears. I'm on a MacBook Air M2.

**Comment by thebarbican19** [comment] 2023-08-31 16:48
Hi @giuliomagnifico, this is actually a feature, not a bug but the UX is less than ideal so will work to improve on that. Right now, the states are...

1. **Time** (Shows the Countdown Time)
2. **Percentage** (Shows Percentage)
3. **Empty** (Shows only the icon, no text)
4. **Removed** (Removes Menu Bar icon altogether and adds Dock Icon instead)

You just click to toggle through all of these. 

I am going to close this issue unless there is something I a missing here? I will open another relating to a more detailed settings menu so I can get some overall feedback regarding that.

**Comment by ScienceOwl13** [comment] 2023-09-05 21:20
This may be unrelated, but I'm experiencing a problem where when  my computer is plugged in, the battery percentage is shown, however when it is unplugged, no matter the state of the icon, it simply shows the battery with it fully charged (which it is.)


Not plugged in:
<img width="63" alt="image" src="https://github.com/thebarbican19/BatteryBoi/assets/71343047/cdc7b5c7-f631-4242-8ac9-fd5b461fb1fd">

Plugged in:
<img width="63" alt="image" src="https://github.com/thebarbican19/BatteryBoi/assets/71343047/aca03101-3896-418b-a99e-ec487e1fe6e9">

**Comment by thebarbican19** [comment] 2023-09-06 02:44
Hi @ScienceOwl13, I have just pushed a new version (2.2.2). Please check for a new update in the app and install the new version as this is resolved. Please confirm it is by letting me know otherwise or closing the issue. Thanks.

**Closed** 2023-09-06 16:33 UTC
